[tools]
bat = "latest"
bun = "latest"
codex = "latest"
fd = "latest"
uv = "latest"
go = "latest"
java = "21"
node = "latest"
rust = "latest"
starship = "latest"
tree-sitter = "latest"
ghq = "latest"
"aqua:k1LoW/git-wt" = "latest"
"github:ogulcancelik/herdr" = "latest"
stylua = "latest"
ruff = "latest"
golangci-lint = "latest"
"npm:@fsouza/prettierd" = "latest"
"npm:eslint_d" = "latest"
